[versions]
h2 = "2.4.240"
sqlite = "3.50.2.0"

[libraries]
h2 = { module = "com.h2database:h2", version.ref = "h2" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }